# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do# add actions here: https://docs.fastlane.tools/actions
    create_xcframework(
        workspace: './EasyMQTTKit.xcworkspace',
        scheme: 'EasyMQTTKit',
        destinations: ['iOS', 'maccatalyst'],
        xcframework_output_directory: './xcframework'
    )
    cleanup
  end

  lane :cleanup do
    sh("find ../xcframework/ -type f -name '*.swiftinterface' -print0 | xargs -0 sed -i '' -e  's/CocoaMQTT\.//g'")
  end
end
